"""empty message

Revision ID: 70bec0e6cb87
Revises: eae8cbe4d95f
Create Date: 2024-02-09 12:56:07.100238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bec0e6cb87'
down_revision = 'eae8cbe4d95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_emotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_emotion', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
