"""empty message

Revision ID: e0bd266b074c
Revises: 
Create Date: 2024-01-30 17:30:40.471107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bd266b074c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('date_stamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], name=op.f('fk_likes_emotion_id_emotions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('emotion_intensity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], name=op.f('fk_users_emotions_emotion_id_emotions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_emotions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_emotions')
    op.drop_table('likes')
    op.drop_table('users')
    op.drop_table('emotions')
    # ### end Alembic commands ###
